name: Labeled ERPNext Task

on:
  workflow_call:
    secrets:
      webhook_token:
        required: true
        description: 'Token for ERPNext API authentication'

jobs:
  create-task:
    runs-on: self-hosted-erpnext

    steps:
      - name: Format Payload
        run: |
          sanitize() {
            echo "$1" | jq -R '.' | sed 's/^"//;s/"$//'
          }

          SANITIZED_TITLE=$(sanitize "${{ github.event.issue.title }}")
          SANITIZED_BODY=$(sanitize "${{ github.event.issue.body }}")

          echo '{
            "subject": "GH#${{ github.event.issue.number }} - '"$SANITIZED_TITLE"'",
            "project": "${{ github.event.label.name }}",
            "status": "Open",
            "description": "<p><a href=\"${{ github.event.issue.html_url }}\">GH#${{ github.event.issue.number }}</a></p><br>'"$SANITIZED_BODY"'"
          }' > payload.json

      - name: Make API Request to ERPNext
        run: |
          curl --fail -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.webhook_token }}" -d @payload.json https://erp.wunderbyte.at/api/resource/Task
